POST https://crudcrud.com/api/77ac29231e134a1cbba000a0db30ad1b/unicorn
Content-Type: application/json

{   "name": "Западный Единорог",
    "tail_color": "black"
}

###
PUT https://crudcrud.com/api/77ac29231e134a1cbba000a0db30ad1b/unicorn/670e7deda0a8cd03e818aa7a
Content-Type: application/json

{"tail_color": "green"}

###
GET https://crudcrud.com/api/77ac29231e134a1cbba000a0db30ad1b/unicorn/670e7deda0a8cd03e818aa7a
Accept: application/json

###
DELETE https://crudcrud.com/api/77ac29231e134a1cbba000a0db30ad1b/unicorn/670e734ba0a8cd03e818aa4c
Accept: application/json


###




